--工作流定义表
CREATE TABLE [dbo].[FlowDefinition](
	[FlowId] [UNIQUEIDENTIFIER] NOT NULL,
	[FlowName] [NVARCHAR](100) NOT NULL,
	[Definition] [NVARCHAR](MAX) NOT NULL,
	[DefinitionId] [NVARCHAR](100) NOT NULL,
	[DefinitionVersion] [INT] NOT NULL,
	[Description] [NVARCHAR](500) NULL,
	[EntryPoint] [NVARCHAR](500) NULL,
	[EntryPointPath] [NVARCHAR](100) NULL,
	[CreateTime] [DATETIME] NOT NULL,
	[Creator] [NVARCHAR](50) NULL,
 CONSTRAINT [PK_FlowDefinition_1] PRIMARY KEY CLUSTERED 
(
	[FlowId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

--启用 Service Broker
ALTER DATABASE WorkflowCore SET NEW_BROKER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE WorkflowCore SET ENABLE_BROKER;

